#!/bin/sh

case "$1" in -h|-H|-help|--help)
	cat <<EOT
Usage: ${0##*/}
Env:   CC       explicit "cc" compiler to use
       AR       explicit "ar" to use
       RANLIB   explicit "ranlib" to use
       CFLAGS   explicit compiler options to use
EOT
	exit 0
esac

if [ -z "$CC" ]; then
	if command -v gcc > /dev/null; then
		CC=gcc
	elif command -v clang > /dev/null; then
		CC=clang
	elif command -v cc > /dev/null; then
		CC=cc
	else
		echo "Could not guess name of compiler, please set CC" >&2
		exit 2
	fi
fi

echo "CC=$CC"
: ${AR:=ar}
echo "AR=$AR"
: ${RANLIB:=ranlib}
echo "RANLIB=$RANLIB"

if [ "${CFLAGS+set}" != "set" ]; then
	case "$CC" in
		*gcc*|*clang*)
			CFLAGS=-O2
			;;
		*)
			CFLAGS=-O
			;;
	esac
fi
echo "CFLAGS=$CFLAGS"

set -ev
LIB=libBlocksRuntime.a
SRC=BlocksRuntime
! test -e $LIB || rm $LIB
"$CC" -c $CFLAGS -o $SRC/data.o $SRC/data.c &&
"$CC" -c $CFLAGS -o $SRC/runtime.o -I . $SRC/runtime.c &&
"$AR" cr $LIB $SRC/data.o $SRC/runtime.o &&
"$RANLIB" $LIB
