#!/bin/sh
: ${CC:=gcc}
echo "CC=$CC"
: ${AR:=ar}
echo "AR=$AR"
: ${RANLIB:=ranlib}
echo "RANLIB=$RANLIB"
: ${CFLAGS:=-O2}
echo "CFLAGS=$CFLAGS"
set -v
LIB=libBlocksRuntime.a
SRC=BlocksRuntime
if test -f $LIB; then rm $LIB; fi
"$CC" -c $CFLAGS -o $SRC/data.o $SRC/data.c \
&& "$CC" -c $CFLAGS -Wno-discard-qual -o $SRC/runtime.o -I . $SRC/runtime.c \
&& "$AR" cr $LIB $SRC/data.o $SRC/runtime.o \
&& "$RANLIB" $LIB
